# Generated by Django 3.1.7 on 2022-02-21 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Organization Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization City')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['created_at'],
                'permissions': (('view_tasks', 'Can view tasks'), ('change_tasks', 'Can change a task')),
            },
        ),
    ]
