# Generated by Django 3.1.7 on 2022-02-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['created_at'], 'permissions': [('create_project', 'Can create project'), ('read_project', 'Can read project')], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
